DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE ODONTOLOGOS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMEROMATRICULA INT NOT NULL,
    NOMBRE  VARCHAR (25) NOT NULL,
    APELLIDO VARCHAR (25) NOT NULL
)

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '0000','JUAN','PEREZ');